% ----------------------------------------------------------------------
%% Common Phrases
% ----------------------------------------------------------------------
instructions.cont = 'Press any key to continue.';

instructions.break = {
    'Break:'; ...
    'Please take a moment to rest your eyes'; ...
    'When you''re ready, press any key to continue'; ...
    };

instructions.total = 'Your total credits:';

% Hacky workaround for annoying psychtoolbox textbounds behaviour.
instructions.linespace1 = '|                                                                         ';
instructions.linespace2 = '                                                                         |';

% ----------------------------------------------------------------------
%% Opening
% ----------------------------------------------------------------------
instructions.opening = {
    'Hello.'; ...
    'Welcome to the 9 Line Slot Task.'; ...
    'In this experiment you will play a simple slot machine.'; ...
    'It looks like this:'; ...
    'When you play each reel will spin just like a slot machine...'; ...
    'If three symbols line up accross the centre a win occurs.'; ...
    'Nice!'; ...
    'When a match occurs the centre symbol will display the amount won'; ...
    'If the centre position doesn''t match you do not win credits'; ...
    ':''('; ...
    'To begin you will play a series of practice spins.'; ...
    'During this period feel free to ask the experimenter any questions'; ...
    'OK let''s go!'
    };

% ----------------------------------------------------------------------
%% Introduce Task
% ----------------------------------------------------------------------
instructions.taskIntro = {
    'You have been given '; ...
    'credits to play'; ...
    'You can keep any credits remaining at the end of the experiment'; ...
	'x credits = $1.00'; ...
    'x credit = 1c'; ...
    'We use a random process to determine the outcome of each spin'; ...
    'So the amount won is different in each session'; ...
    };

% ----------------------------------------------------------------------
%% Explain 9 lines
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
%% Explain Betting
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
%% Practice
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
%% Choose Bet
% ----------------------------------------------------------------------

instructions.left = 'Press left';
instructions.right = 'Press right';

% Bet High
instructions.betH = {
    'Bet 10'; ...
    '10 credits per line x 9 lines'; ...
    '90 credits per spin'; ...
    'remaining'; ...
    };

% Bet Low
instructions.betL = {
    'Bet 1'; ...
    '1 credits per line x 9 lines'; ...
    '9 credits per spin'; ...
    'remaining'; ...
    };

% ----------------------------------------------------------------------
%% Fin
% ----------------------------------------------------------------------

