function [instructions] = setup_instructions()
% ----------------------------------------------------------------------
% [instructions] = setup_instructions()
% ----------------------------------------------------------------------
% Goal of the function :
% Lay out some text for task instructions
% ----------------------------------------------------------------------
% Input(s) :
% none
% ----------------------------------------------------------------------
% Output(s):
% instructions — full of text snippets for intro sequence
% ----------------------------------------------------------------------
% Function created by Dan Myles (dan.myles@monash.edu)
% Last update : June 2021
% Project : 9_Line_Slots_Task
% Version : 2021a
% ----------------------------------------------------------------------

% ----------------------------------------------------------------------
%% Common Phrases
% ----------------------------------------------------------------------
instructions.cont = 'Press any key to continue.';

% ----------------------------------------------------------------------
%% Opening
% ----------------------------------------------------------------------
instructions.opening = {
    'Hello.'; ...
    'Welcome to the 9 Line Slot Task.'; ...
    'In this experiment you will play a simple slot machine.'; ...
    'It looks like this:'; ...
    'Each reel will spin just like a slot machine.'; ...
    'If three symbols line up a win occurs...'; ...
    'Nice!'; ...
    'When a match occurs the centre symbol will display the amount won.'; ...
    'If the centre position doesn''t match you do not win credits.'; ...
    ':''(';
    };

% ----------------------------------------------------------------------
%% Explain 9 lines
% ----------------------------------------------------------------------

instructions.lines = {
    'There are 5 different symbols:'; ...
    'Match 3 of the same symbol and the machine will payout!'; ...
    'There are 9 different ways that three symbols can match...';
    };

% ----------------------------------------------------------------------
%% Explain Betting
% ----------------------------------------------------------------------

instructions.betting = {
    'Before each spin you will be shown your total credits.'; ...
    'You will also be given a choice between two slot machine games.'; ...
	'Each game is subtly different.'; ...
    'Your task is to determine which of the two games is the most advantageous.'; ...
    'Every bet will cost 90 credits.'; ...
    'That''s 10 credits for each of the 9 ways that a win can occur.'
    };

% ----------------------------------------------------------------------
%% Explain Fixation Cross
% ----------------------------------------------------------------------

instructions.fixation = {
    'You may have noticed this symbol during the previous demonstration.'; ...
    'It''s is called a ''fixation cross''.'; ...
    'The fixation cross will appear moments before the final symbol on each trial.'; ...
    'This point indicates where the outcome will be displayed.'; ...
    'Whenever it appears, try to remain still and gently focus your gaze on that point.'; ...
    'Try to keep your gaze still for a moment following the outcome display.'; ...
    'This will help to improve the accuracy of the EEG recording.'; ...
    'In the next sequence practice keeping your eyes still and focused on the fixation cross.'
    };

% ----------------------------------------------------------------------
%% Introduce Task
% ----------------------------------------------------------------------
instructions.taskIntro = {
    'You have been given '; ...
    ' credits to play'; ...
    '1,000 credits = $1'; ...
    '10 credits = 1c'; ...
    'We will pay you the final credit balance at the end of the experiment.'; ...
    'A random process is used to determine the outcome of each spin.'; ...
    'So the final credit balance will depend on how many wins and losses occur.'; ...
    'And how often you decide to bet on each of the two games.'};

% end of function.
end